language: node_js
node_js:
- '4'
- stable
services: mongodb
deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: sF5vv/uOCWKhdgjpS3c9ZUiG9C41ujdILRhAZMKXTlaiG2ok+ILQWeht93kLUCKTKzIoCGcZtrFtfGcpB7mmyoOVWpUkIWQ+437ah34rTf/VSABRYVCdI3w2zhm3ZMd5Jo4O7pq+4DEkpxMgXlXrdwyIYBMcR8AJj/0GuavNoOuACRKmqaIIq1SOdSmFvlPJ54q2gP6SjaHcY2MJhyNcoUBdMuNM+owFYkezdZko6kMCGtMcX+3FVN/NsNfFYGKnbqGXeXseTBXlRc/vxUNd/BZzez80IhGWwUnwISS0mJVOdTRuoKIlZVcOAunfIMjcFtdhHZNCvW8fuN6yyMFS2JYFUX9WyFGWUcAswc8K2KMHY3yW1C6Xt9ccp6jU2jdgpO9FKwfRBSilysT8DeLzPVpEg9SSjAzX4bQNLmteAG82FUov8QWIT0fbb3kUee3V+Uuqi46thU0x9uasorzaYXCz32BgoS0aFsfTmCS+cEPZ3LfHV2KJi46artFF3XM/4+4cr/ivzEpFDqAuiN/22ZN3lgV1vBVDnVFptuA2Z9TDNwp/dw+S20EuYGyYQe1NOC1ZWWAdSRFz4FUndAJx6PFctJorXFtTD697BD+STDoF2xVi3I/CyPdaLD633ROhklBoG9WwV29cO2t9iLhX6oqsiTkfH4rzLSFgFKiife8=
  on:
    tags: true
    repo: trailsjs/trailpack-mongoose
    node: stable
