language: node_js
node_js:
- '4'
- stable
services: mongodb
deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: Jvguvm/Ila5H7Qd6hknN1+ogoT+95WnMDRo8kZLYutyaLG0O6sktcSEXE4xjwqZH3DpYfNsieCdA3bAen7ahzfrsQ1gp8ru6xAiGze23dxDUQWdKafhvG7NxfX8qOKXnhYe1PH4sqZ147FHooV2wzi2Wz4kAL+sHdCV5yShC52Opk1z3F7eiQGLwEDmJGSu8M7QAueD7wX8QQ//h8ZHoHp+vp9GqYGXRBztXnWmLfMvVNFiaS++Nn6jnTY20cz/hkPzYxqCfxm2P1oR3duJcVzkVUCMAEKunwljCyyP+KZDou3WoBsF9Jjnuu6uZDCVssKyiCwKOU2VHfNsmfRZmVRnb42KNXEH3NIgoawRyZ5P6PcuBWxW3ZLO+MjjoCtdBIr7RARsBc+oLP5jb1jO+uKuSyZUHhxwgl+KzVjvwn0fcrGZGnFZHTT42SpnkLDx9DmUPDVoMkfm+5zeU6DDrHhwvYhKN94cDwFr4o4wxIyXjjRfAzu0vptpB7QIpPHICXP1jw58VB1RKLRefl6Fz+tu9p2gVpo0I/kZCJuHouLCz2uNOweD+uj4gQZAXA+FU9NtWfqkvlxVLJ1M4TredLFVFZXcL9A/NACtuDxaAQcRSjy/u3gBT8qYpO3Iis9XeLXDAWXobETJbUyzjHOiWR2ow8xI5vRBdiiBURIDmNx8=
  on:
    tags: true
    repo: trailsjs/trailpack-mongoose
    node: stable
